dune = dune $(1) $(DUNE_$(1)_FLAGS)

elpi/dune: elpi/dune.in
	@rm -f $@
	@echo "; generated by make, do not edit" > $@
	@if $$(coqc --version | grep -q "8.19\|8.20") ; then \
	  sed -e 's/@@STDLIB_THEORY@@//' $< >> $@ ; \
	else \
	  sed -e 's/@@STDLIB_THEORY@@/(theories Stdlib)/' $< >> $@ ; \
	fi
	@chmod a-w $@

all: elpi/dune theories-stdlib/dune
	$(call dune,build)
	$(call dune,build) builtin-doc
.PHONY: all

build-core: elpi/dune theories-stdlib/dune
	$(call dune,build) theories
	$(call dune,build) builtin-doc
.PHONY: build-core

build-apps: elpi/dune theories-stdlib/dune
	$(call dune,build) $$(find apps -type d -name theories)
.PHONY: build-apps

build: elpi/dune theories-stdlib/dune
	$(call dune,build) -p coq-elpi @install
	$(call dune,build) builtin-doc
.PHONY: build

all-tests: test-core test-stdlib test-apps test-apps-stdlib
.PHONY: all-tests

test-core: elpi/dune theories-stdlib/dune
	$(call dune,runtest) tests
	$(call dune,build) tests
.PHONY: test-core

test-apps: elpi/dune theories-stdlib/dune
	$(call dune,build) $$(find apps -type d -name tests)
.PHONY: test-apps

test-apps-stdlib: elpi/dune theories-stdlib/dune
	$(call dune,build) $$(find apps -type d -name tests-stdlib)
.PHONY: test-apps-stdlib

test-stdlib: elpi/dune theories-stdlib/dune
	$(call dune,build) tests-stdlib
.PHONY: test-stdlib

all-examples: examples examples-stdlib
.PHONY: all-examples

examples: elpi/dune theories-stdlib/dune
	$(call dune,build) examples
.PHONY: examples

examples-stdlib: elpi/dune theories-stdlib/dune
	$(call dune,build) examples-stdlib
.PHONY: examples-stdlib

theories-stdlib/dune: theories-stdlib/dune.in
	@rm -f $@
	@echo "; generated by make, do not edit" > $@
	@if $$(coqc --version | grep -q "8.19\|8.20") ; then \
		sed -e 's/@@STDLIB@@//' $< >> $@ ; \
	else \
		sed -e 's/@@STDLIB@@/Stdlib/' $< >> $@ ; \
	fi
	@chmod a-w $@

doc: build
	@echo "########################## generating doc ##########################"
	@mkdir -p doc
	@$(foreach tut,$(wildcard examples/tutorial*$(ONLY)*.v),\
		echo ALECTRYON $(tut) && OCAMLPATH=$(shell pwd)/_build/install/default/lib ./etc/alectryon_elpi.py \
		    --frontend coq+rst \
			--output-directory doc \
		    --pygments-style vs \
			-R $(shell pwd)/_build/install/default/lib/coq/user-contrib/elpi_elpi elpi_elpi \
			-R $(shell pwd)/_build/install/default/lib/coq/user-contrib/elpi elpi \
			$(tut) &&) true
	@cp ./_build/default/examples/stlc.txt doc/
	@cp etc/tracer.png doc/

clean:
	$(call dune,clean)
.PHONY: clean

install: elpi/dune
	$(call dune,install) coq-elpi
.PHONY: install

nix:
	nix-shell --arg do-nothing true --run "updateNixToolBox && genNixActions"
.PHONY: nix
