(executable
 (name gen_doc)
 ; this doc depends on the myExtension library, where the
 ; new builtins are declared
 (libraries myExtension.plugin))

(rule
 ; myExtension.elpi contains the doc of the builtins defined in the myExtension plugin
 (targets myExtension.elpi)
 (deps gen_doc.exe)
 (mode promote)
 (action (run ./gen_doc.exe)))

; (install
;  (files myExtension.elpi)
;  (section doc)
;  (package ext))
